#!/usr/bin/env python3
"""
generate_3sat_mnist_cnf.py  (fixed gate_NOT signature)

Generates a 3-CNF (DIMACS) file that encodes the **existence** of int8 weights for a
small convolutional neural net (conv -> ReLU -> FC -> argmax) that correctly classifies
a small set of training examples.

USAGE:
    python generate_3sat_mnist_cnf.py --out problem.cnf --samples 1 --img_h 6 --img_w 6 \
        --conv_filters 1 --kernel 3 --fc_hidden 8

WARNING:
    This is a full bit-blast reduction. For realistic MNIST (28x28, 8 filters, FC 128)
    the CNF will be extremely large. The script is intentionally explicit (no shortcuts).
"""
import argparse
import numpy as np
import sys

# -------------------------
# CNF builder and logic gates
# -------------------------
class CNFBuilder:
    def __init__(self):
        self.var_count = 0
        self.clauses = []
        self.names = {}  # optional mapping name->varid for debugging (not used for all vars)

    def new_var(self, name=None):
        self.var_count += 1
        if name:
            self.names[name] = self.var_count
        return self.var_count

    def add_clause(self, lits):
        # lits: list of integers (positive for var, negative for negation)
        assert all(isinstance(x, int) and x != 0 for x in lits)
        self.clauses.append(list(lits))

    def add_unit(self, var, val=True):
        self.add_clause([var if val else -var])

    def write_dimacs(self, filename):
        with open(filename, 'w') as f:
            f.write("c Generated by generate_3sat_mnist_cnf.py\n")
            f.write("c var_count: %d\n" % self.var_count)
            f.write("p cnf %d %d\n" % (self.var_count, len(self.clauses)))
            for c in self.clauses:
                f.write(" ".join(str(x) for x in c) + " 0\n")

# Instantiate global CNF builder used by the gate functions
cnf = CNFBuilder()

# ----- Basic boolean gates encoded into CNF (3-CNF clauses) -----
# Following standard Tseitin encodings with all clauses size <= 3.

def gate_NOT(b):
    """z = NOT b"""
    z = cnf.new_var()
    # (b or z) & (~b or ~z)
    cnf.add_clause([ b,  z])
    cnf.add_clause([-b, -z])
    return z

def gate_AND(a, b):
    """z = a & b"""
    z = cnf.new_var()
    cnf.add_clause([-a, -b,  z])
    cnf.add_clause([ a, -z])
    cnf.add_clause([ b, -z])
    return z

def gate_OR(a, b):
    """z = a OR b"""
    z = cnf.new_var()
    cnf.add_clause([ a,  b, -z])
    cnf.add_clause([-a,  z])
    cnf.add_clause([-b,  z])
    return z

def gate_XOR(a, b):
    """z = a XOR b"""
    z = cnf.new_var()
    # (a or b or ~z) & (~a or ~b or ~z) & (a or ~b or z) & (~a or b or z)
    cnf.add_clause([ a,  b, -z])
    cnf.add_clause([-a, -b, -z])
    cnf.add_clause([ a, -b,  z])
    cnf.add_clause([-a,  b,  z])
    return z

def gate_XNOR(a, b):
    t = gate_XOR(a, b)
    return gate_NOT(t)

# ---- Multi-bit utilities (LSB-first bitvectors) -----

def mk_const_bitvec(value, bits):
    """Create a bitvector constant (two's complement for negatives) as unit clauses."""
    # value interpreted as signed integer in range representable by 'bits'
    mask = (1 << bits) - 1
    if value < 0:
        value = (1 << bits) + value
    vec = []
    for i in range(bits):
        v = cnf.new_var()
        bit = (value >> i) & 1
        cnf.add_unit(v, bool(bit))
        vec.append(v)
    return vec

def mk_fresh_bitvec(bits, basename=None):
    """Create a fresh bitvector of length bits (unconstrained)."""
    return [cnf.new_var(name=(basename + "_b%d" % i) if basename else None) for i in range(bits)]

def sign_extend(vec, new_bits):
    """Sign-extend LSB-first bitvector vec to length new_bits."""
    old = len(vec)
    assert new_bits >= old
    sign = vec[-1]
    out = list(vec)
    for i in range(old, new_bits):
        z = cnf.new_var()
        # enforce z <-> sign  : (¬sign ∨ z) & (sign ∨ ¬z)
        cnf.add_clause([-sign, z])
        cnf.add_clause([ sign, -z])
        out.append(z)
    return out

# ---- Adders & multipliers (bit-blasted) -----

def half_adder(a, b):
    s = gate_XOR(a, b)
    c = gate_AND(a, b)
    return s, c

def full_adder(a, b, cin):
    # sum = a XOR b XOR cin
    t = gate_XOR(a, b)
    s = gate_XOR(t, cin)
    # carry = majority(a,b,cin) = (a&b) | (a&cin) | (b&cin)
    c1 = gate_AND(a, b)
    c2 = gate_AND(a, cin)
    c3 = gate_AND(b, cin)
    c12 = gate_OR(c1, c2)
    c = gate_OR(c12, c3)
    return s, c

def ripple_adder(A, B):
    """Unsigned adder: returns sum bits (LSB-first) of length max(len(A),len(B)) + 1 (carry out)"""
    n = max(len(A), len(B))
    # pad
    Aa = list(A) + [mk_const_bitvec(0,1)[0]] * (n - len(A))
    Bb = list(B) + [mk_const_bitvec(0,1)[0]] * (n - len(B))
    S = []
    carry = mk_const_bitvec(0,1)[0]
    for i in range(n):
        s, carry = full_adder(Aa[i], Bb[i], carry)
        S.append(s)
    S.append(carry)
    return S

def add_bitvecs(A, B, out_len=None):
    S = ripple_adder(A, B)
    if out_len is None:
        return S
    # truncate or extend to out_len
    if len(S) >= out_len:
        return S[:out_len]
    else:
        # pad with zeros
        pad = [mk_const_bitvec(0,1)[0] for _ in range(out_len - len(S))]
        return S + pad

def multiply_unsigned(A, B):
    """Basic shift-add unsigned multiply. A (n bits) * B (m bits) => product (n+m bits)."""
    n = len(A)
    m = len(B)
    prod = [mk_const_bitvec(0,1)[0] for _ in range(n + m)]
    for j in range(m):
        # partial = [A[i] & B[j] for i in range(n)] shifted by j
        partial = [mk_const_bitvec(0,1)[0] for _ in range(j)]  # shift
        for i in range(n):
            partial.append(gate_AND(A[i], B[j]))
        partial += [mk_const_bitvec(0,1)[0] for _ in range((n + m) - len(partial))]
        # add partial to prod
        prod = add_bitvecs(prod, partial, out_len=n + m)
    return prod

def multiply_signed(a_bits, b_bits, result_bits):
    """
    Signed multiply via sign-extension: sign-extend operands to double width, do unsigned multiply,
    and take lower 'result_bits' bits (which correspond to correct two's-complement product).
    """
    n = len(a_bits)
    m = len(b_bits)
    ext = max(n, m) * 2  # extend to 2*max width
    A = sign_extend(a_bits, ext)
    B = sign_extend(b_bits, ext)
    prod = multiply_unsigned(A, B)  # length ext+ext
    # prod is LSB-first; take lower 'result_bits'
    if result_bits <= len(prod):
        return prod[:result_bits]
    else:
        # pad with zeros (unlikely)
        pad = [mk_const_bitvec(0,1)[0] for _ in range(result_bits - len(prod))]
        return prod + pad

# ---- Comparators & misc -----

def xor_chain_bits(A, B):
    assert len(A) == len(B)
    outs = []
    for i in range(len(A)):
        outs.append(gate_XOR(A[i], B[i]))
    return outs

def xnor_bit(a, b):
    t = gate_XOR(a, b)
    return gate_NOT(t)

def unsigned_greater(A, B):
    """Return var representing A > B for unsigned bitvectors (MSB index high->low)."""
    n = max(len(A), len(B))
    # pad to equal length
    Aa = list(A) + [mk_const_bitvec(0,1)[0]] * (n - len(A))
    Bb = list(B) + [mk_const_bitvec(0,1)[0]] * (n - len(B))
    # build eq_prefix starting True
    eq_prefix = mk_const_bitvec(1,1)[0]
    gt = mk_const_bitvec(0,1)[0]
    # iterate from MSB downto LSB
    for i in range(n-1, -1, -1):
        not_b = gate_NOT(Bb[i])
        ai_and_notbi = gate_AND(Aa[i], not_b)
        term = gate_AND(eq_prefix, ai_and_notbi)
        gt = gate_OR(gt, term)
        # eq_prefix = eq_prefix && XNOR(Ai,Bi)
        xnor = xnor_bit(Aa[i], Bb[i])
        eq_prefix = gate_AND(eq_prefix, xnor)
    return gt

def signed_greater(A, B):
    """Return var representing signed A > signed B. Two's complement bitvectors (LSB-first)."""
    assert len(A) == len(B)
    signA = A[-1]
    signB = B[-1]
    not_signA = gate_NOT(signA)
    not_signB = gate_NOT(signB)
    # case1: signA != signB -> if A pos and B neg then true
    sign_diff = gate_XOR(signA, signB)
    a_pos_b_neg = gate_AND(not_signA, signB)
    case_diff = a_pos_b_neg  # implies A>B when signs differ
    # case2: signs equal -> if positive compare unsigned, if negative reverse
    both_pos = gate_AND(not_signA, not_signB)
    both_neg = gate_AND(signA, signB)
    ug = unsigned_greater(A, B)
    # eq bits:
    eq = mk_const_bitvec(1,1)[0]
    for i in range(len(A)):
        bit_xnor = xnor_bit(A[i], B[i])
        eq = gate_AND(eq, bit_xnor)
    ug_or_eq = gate_OR(ug, eq)
    unsigned_less = gate_NOT(ug_or_eq)
    # when both negative, result = unsigned_less
    case_both_neg = gate_AND(both_neg, unsigned_less)
    case_both_pos = gate_AND(both_pos, ug)
    case_equal_signs = gate_OR(case_both_pos, case_both_neg)
    # final result = (sign_diff AND case_diff) OR (NOT sign_diff AND case_equal_signs)
    not_sign_diff = gate_NOT(sign_diff)
    left = gate_AND(sign_diff, case_diff)
    right = gate_AND(not_sign_diff, case_equal_signs)
    res = gate_OR(left, right)
    return res

# ---- High-level network construction -----

def quantize_image_to_int8(img):
    """Convert 0..255 uint8 image to signed int8 two's complement representation.
       Returns list of bitvectors (LSB-first) for each pixel.
    """
    h, w = img.shape
    bits = 8
    out = []
    for y in range(h):
        for x in range(w):
            val = int(img[y,x])
            signed = val - 128  # map 0..255 -> -128..127
            bvec = mk_const_bitvec(signed, bits)
            out.append(bvec)
    return out  # list of bitvecs per pixel

def build_network_cnf(images, labels, cfg):
    """
    images: list of numpy arrays shape (H,W)
    labels: list of ints
    cfg: dictionary of network config
    """
    samples = len(images)
    H = cfg['img_h']; W = cfg['img_w']
    in_ch = cfg['in_ch']
    k = cfg['kernel']
    filters = cfg['conv_filters']
    fc_hidden = cfg['fc_hidden']
    qbits = cfg['qbits']  # 8

    # create weight variables (int8) for conv and fc
    # conv weights: [f][c][kh][kw] each 8-bit
    conv_w = {}
    for f in range(filters):
        conv_w[f] = {}
        for c in range(in_ch):
            conv_w[f][c] = {}
            for iy in range(k):
                conv_w[f][c][iy] = {}
                for ix in range(k):
                    conv_w[f][c][iy][ix] = mk_fresh_bitvec(qbits, basename=f"w_conv_f{f}_c{c}_{iy}_{ix}")

    # conv bias (int8) per filter
    conv_b = [mk_fresh_bitvec(qbits, basename=f"b_conv_f{f}") for f in range(filters)]

    # FC weights: shape [out=10][in=flattened]
    out_h = H - k + 1
    out_w = W - k + 1
    flat_len = filters * out_h * out_w
    fc_w = {}
    for o in range(10):
        fc_w[o] = {}
        for j in range(flat_len):
            fc_w[o][j] = mk_fresh_bitvec(qbits, basename=f"w_fc_o{o}_j{j}")
    fc_b = [mk_fresh_bitvec(qbits, basename=f"b_fc_o{o}") for o in range(10)]

    # For each sample create input bitvecs
    inputs = []
    for s in range(samples):
        imgs = images[s]
        pix_bitvecs = quantize_image_to_int8(imgs)
        inputs.append(pix_bitvecs)  # list of H*W bitvecs each length 8

    # For each sample, build forward pass bit-blasted
    logits_per_sample = []
    for s in range(samples):
        pix = inputs[s]
        # convolution: compute outputs per filter per location
        conv_out_int8 = []  # will hold bitvectors length qbits
        # For each filter
        for f in range(filters):
            for oy in range(out_h):
                for ox in range(out_w):
                    # accumulator width: choose 20 bits to be safe
                    ACC_BITS = 20
                    acc = [mk_const_bitvec(0,1)[0] for _ in range(ACC_BITS)]
                    # perform sum over kernel and in_ch
                    for c in range(in_ch):
                        for ky in range(k):
                            for kx in range(k):
                                iy = oy + ky
                                ix = ox + kx
                                pixel_vec = pix[iy * W + ix]  # 8-bit
                                weight_vec = conv_w[f][c][ky][kx]  # 8-bit
                                # multiply signed -> 16-bit product, then extend to ACC_BITS
                                prod = multiply_signed(pixel_vec, weight_vec, result_bits=16)
                                prod_ext = sign_extend(prod, ACC_BITS)
                                acc = add_bitvecs(acc, prod_ext, out_len=ACC_BITS)
                    # add bias
                    bias_ext = sign_extend(conv_b[f], ACC_BITS)
                    acc = add_bitvecs(acc, bias_ext, out_len=ACC_BITS)
                    # apply ReLU + saturate to int8: out = clamp(max(acc,0), 0, 127)
                    sign_bit = acc[-1]
                    not_sign = gate_NOT(sign_bit)
                    # test if any upper bits (from bit 8 up) are set => >=128 (we check bits 8..ACC_BITS-1)
                    upper_or = mk_const_bitvec(0,1)[0]
                    for b_i in range(8, ACC_BITS):
                        upper_or = gate_OR(upper_or, acc[b_i])
                    not_upper_or = gate_NOT(upper_or)
                    cond_pos_large = gate_AND(not_sign, upper_or)
                    cond_pos_small = gate_AND(not_sign, not_upper_or)
                    # constant 127 bitvec
                    const_127 = mk_const_bitvec(127, 8)
                    out_bits = []
                    for bitidx in range(8):
                        term1 = gate_AND(cond_pos_large, const_127[bitidx])
                        term2 = gate_AND(cond_pos_small, acc[bitidx])
                        ob = gate_OR(term1, term2)
                        out_bits.append(ob)
                    conv_out_int8.append(out_bits)
        # flatten conv_out_int8 to feature vector bitvec per element
        flat = conv_out_int8  # list of bitvecs length flat_len
        # fully connected: compute logits for 10 outputs
        logits = []
        for o in range(10):
            # accumulator sized large enough: each product is 16 bits, sum across flat_len
            ACC_BITS_FC = 24
            acc = [mk_const_bitvec(0,1)[0] for _ in range(ACC_BITS_FC)]
            for j in range(flat_len):
                inp_vec = flat[j]
                w_vec = fc_w[o][j]
                prod = multiply_signed(inp_vec, w_vec, result_bits=16)
                prod_ext = sign_extend(prod, ACC_BITS_FC)
                acc = add_bitvecs(acc, prod_ext, out_len=ACC_BITS_FC)
            # add bias
            bias_ext = sign_extend(fc_b[o], ACC_BITS_FC)
            acc = add_bitvecs(acc, bias_ext, out_len=ACC_BITS_FC)
            # logits keep as signed ACC_BITS_FC vector (no activation)
            # For comparison later we'll convert to 8-bit saturated logits (clamp to [-128,127])
            sign_bit = acc[-1]
            # clamp positive overflow: if any upper bits beyond 7 set -> saturate to 127 or -128 depending on sign
            upper_or_pos = mk_const_bitvec(0,1)[0]
            for b_i in range(8, ACC_BITS_FC):
                upper_or_pos = gate_OR(upper_or_pos, acc[b_i])
            not_upper_or_pos = gate_NOT(upper_or_pos)
            # when positive and overflow -> 127 ; when negative and overflow -> -128
            const_127 = mk_const_bitvec(127, 8)
            const_neg128 = mk_const_bitvec(-128, 8)
            not_sign = gate_NOT(sign_bit)
            cond_pos_small = gate_AND(not_sign, not_upper_or_pos)
            cond_pos_big = gate_AND(not_sign, upper_or_pos)
            cond_neg_small = gate_AND(sign_bit, not_upper_or_pos)
            cond_neg_big = gate_AND(sign_bit, upper_or_pos)
            out_bits = []
            for bitidx in range(8):
                t_pos_big = gate_AND(cond_pos_big, const_127[bitidx])
                t_pos_small = gate_AND(cond_pos_small, acc[bitidx])
                t_neg_small = gate_AND(cond_neg_small, acc[bitidx])
                t_neg_big = gate_AND(cond_neg_big, const_neg128[bitidx])
                tmp1 = gate_OR(t_pos_big, t_pos_small)
                tmp2 = gate_OR(t_neg_small, t_neg_big)
                ob = gate_OR(tmp1, tmp2)
                out_bits.append(ob)
            logits.append(out_bits)
        logits_per_sample.append(logits)

    # correctness constraints: for each sample, predicted argmax equals label
    for s, lbl in enumerate(labels):
        logits = logits_per_sample[s]
        for o in range(10):
            if o == lbl: continue
            # enforce logits[lbl] > logits[o]
            gt = signed_greater(logits[lbl], logits[o])
            # add clause that gt must be true
            cnf.add_unit(gt, True)

    return

# ------------------------
# main: CLI and demo run
# ------------------------
def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--out", required=True, help="Output DIMACS CNF filename")
    p.add_argument("--samples", type=int, default=1)
    p.add_argument("--img_h", type=int, default=6)
    p.add_argument("--img_w", type=int, default=6)
    p.add_argument("--in_ch", type=int, default=1)
    p.add_argument("--kernel", type=int, default=3)
    p.add_argument("--conv_filters", type=int, default=1)
    p.add_argument("--fc_hidden", type=int, default=8)
    p.add_argument("--qbits", type=int, default=8)
    return p.parse_args()

if __name__ == "__main__":
    args = parse_args()
    cfg = dict(img_h=args.img_h, img_w=args.img_w, in_ch=args.in_ch,
               kernel=args.kernel, conv_filters=args.conv_filters,
               fc_hidden=args.fc_hidden, qbits=args.qbits)
    # For demonstration build tiny random images and labels
    images = []
    labels = []
    for i in range(args.samples):
        img = np.random.randint(0, 256, size=(args.img_h, args.img_w), dtype=np.uint8)
        images.append(img)
        labels.append(int(np.random.randint(0, 10)))
    build_network_cnf(images, labels, cfg)
    cnf.write_dimacs(args.out)
    print("Wrote DIMACS CNF to", args.out)